name: Node.js CI

permissions: read-all
env:
  NODE_ENV: development
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, development]
  push:
    branches:
      - main
      - development
jobs:
  Lint-and-format-test-ubuntu:
    name: check for linting and formatting errors on ubuntu-latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        shell: bash
        run: npm ci
      - name: Lint Codebase
        shell: bash
        run: npm run lint:check
      - name: format Codebase
        shell: bash
        run: npm run format:check
      - name: validate branch name
        shell: bash
        run: npm run validate-branch-name $BRANCH_NAME
      - name: Validate all commits from PR
        if: ${{ github.event_name == 'pull_request' }}
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose --config .commitlintrc.js
# Note: PR checks wont run when there are merge conflicts
